services:
  backend:
    image: ghcr.io/cottons29/job-portal-group-12/backend:latest
    container_name: job_portal_backend
    restart: always
    env_file:
      - .env
    environment:
      PORT: 3080
    ports:
      - "3080:3080"

  frontend:
    image: ghcr.io/cottons29/job-portal-group-12/frontend:latest
    container_name: job_portal_frontend
    restart: always
    ports:
      - "3081:80"
    depends_on:
      - backend

volumes:
  postgres_data:
