import { DataSource } from 'typeorm';
import { Company } from './company.entity';

export async function seedCompanies(dataSource: DataSource) {
  const companyRepo = dataSource.getRepository(Company);
  const count = await companyRepo.count();
  if (count > 0) {
    console.log('Companies already seeded.');
    return;
  }

  console.log('Seeding 100 companies...');

  const companiesData = [
    // --- Technology / IT (25 Companies) ---
    {
      name: 'Smart Axiata',
      industry: 'technology',
      address: 'phnom_penh',
      website: 'https://www.smart.com.kh',
      description: 'Smart Axiata Co., Ltd., Cambodia\'s leading mobile telecommunications operator, currently serves over 8 million subscribers under the "Smart" brand.',
      logoUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Cellcard',
      industry: 'technology',
      address: 'phnom_penh',
      website: 'https://www.cellcard.com.kh',
      description: 'Cellcard is Cambodia\'s longest-serving and only 100% Cambodian-owned mobile communications operator, pioneering telecommunications since 1997.',
      logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Sabay Digital',
      industry: 'technology',
      address: 'phnom_penh',
      website: 'https://www.sabay.com',
      description: 'Sabay Digital is a leading publisher, developer, and distributor of online games, digital content, and media entertainment in Cambodia.',
      logoUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Codingate',
      industry: 'technology',
      address: 'phnom_penh',
      website: 'https://www.codingate.com',
      description: 'Codingate is an award-winning technology company in Cambodia, specializing in software development, web applications, and mobile app design.',
      logoUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Pathmazing',
      industry: 'technology',
      address: 'phnom_penh',
      website: 'https://www.pathmazing.com',
      description: 'Pathmazing is an enterprise software development agency, offering high-end solutions, custom software engineering, and digital transformation.',
      logoUrl: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Nham24',
      industry: 'technology',
      address: 'phnom_penh',
      website: 'https://www.nham24.com',
      description: 'Nham24 is Cambodia\'s first and largest local super-app, offering food delivery, grocery shopping, ride-hailing, and express courier services.',
      logoUrl: 'https://images.unsplash.com/photo-1526367790999-0150786486a9?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'BookMeBus',
      industry: 'technology',
      address: 'phnom_penh',
      website: 'https://www.bookmebus.com',
      description: 'BookMeBus is an award-winning travel booking portal connecting travelers with bus, ferry, and private taxi operators across Southeast Asia.',
      logoUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Morakot Technology',
      industry: 'technology',
      address: 'phnom_penh',
      website: 'https://www.morakot.io',
      description: 'Morakot Technology is a leading fintech company specializing in core banking systems and microfinance software solutions in Southeast Asia.',
      logoUrl: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'MangoByte',
      industry: 'technology',
      address: 'phnom_penh',
      website: 'https://www.mangobyte.com',
      description: 'MangoByte is an agile technology partner providing top-tier web design, search engine optimization, and custom mobile applications.',
      logoUrl: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Last2Ticket Asia',
      industry: 'technology',
      address: 'siem_reap',
      website: 'https://www.last2ticket.asia',
      description: 'Last2Ticket Asia provides advanced e-ticketing solutions and digital event management services for corporate clients across Cambodia.',
      logoUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'SystemOne Cambodia',
      industry: 'technology',
      address: 'phnom_penh',
      website: 'https://www.systemone.com.kh',
      description: 'SystemOne is a leading system integration company specializing in IT infrastructure, networking, cybersecurity, and cloud migration services.',
      logoUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Somjot Tech',
      industry: 'technology',
      address: 'phnom_penh',
      website: 'https://www.somjot.com',
      description: 'Somjot Tech provides innovative IoT solutions, smart parking management systems, and license plate recognition technology for smart buildings.',
      logoUrl: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Ten10 Digital Agency',
      industry: 'technology',
      address: 'phnom_penh',
      website: 'https://www.ten10.co',
      description: 'Ten10 Digital is a full-service creative agency specializing in UX/UI design, brand strategy, content marketing, and custom web experiences.',
      logoUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Geeks in Cambodia',
      industry: 'technology',
      address: 'phnom_penh',
      website: 'https://www.geekscambodia.com',
      description: 'Geeks in Cambodia is the premier online hub for startup news, tech innovation, developer events, and digital culture in Cambodia.',
      logoUrl: 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Bona Tech Solutions',
      industry: 'technology',
      address: 'battambang',
      website: 'https://www.bonatech.com.kh',
      description: 'Bona Tech Solutions delivers specialized agricultural IoT sensors and drone technology for precision farming and water management.',
      logoUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Agile Development Cambodia',
      industry: 'technology',
      address: 'phnom_penh',
      website: 'https://www.agiledev.com.kh',
      description: 'Agile Development Cambodia offers professional training, software consulting, and agile project management coaching for enterprises.',
      logoUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Inlay Cloud',
      industry: 'technology',
      address: 'sihanoukville',
      website: 'https://www.inlaycloud.com',
      description: 'Inlay Cloud offers regional secure web hosting, managed virtual private servers (VPS), and scalable Kubernetes container services.',
      logoUrl: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Phnom Penh Cyber Security',
      industry: 'technology',
      address: 'phnom_penh',
      website: 'https://www.ppcyber.com',
      description: 'PP Cyber Security is Cambodia\'s premier defensive security group, providing penetration testing, vulnerability audits, and incident response.',
      logoUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'CamDev Apps',
      industry: 'technology',
      address: 'siem_reap',
      website: 'https://www.camdevapps.com',
      description: 'CamDev Apps creates custom booking systems, tour operator portals, and hospitality software for the tourism industry in Siem Reap.',
      logoUrl: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Voltra Motors',
      industry: 'technology',
      address: 'phnom_penh',
      website: 'https://www.voltramotors.com',
      description: 'Voltra Motors manufactures and develops eco-friendly electric scooters and smart battery swap networks for clean urban mobility in Cambodia.',
      logoUrl: 'https://images.unsplash.com/photo-1558441719-ff34b0524a24?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Plus1 Innovation',
      industry: 'technology',
      address: 'phnom_penh',
      website: 'https://www.plus1innov.com',
      description: 'Plus1 Innovation develops artificial intelligence models, automatic Khmer speech-to-text systems, and natural language processing solutions.',
      logoUrl: 'https://images.unsplash.com/photo-1677442136019-21780efad99a?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Blue Technology',
      industry: 'technology',
      address: 'phnom_penh',
      website: 'https://www.bluetechnology.com.kh',
      description: 'Blue Technology is an IT consulting firm providing enterprise resource planning (ERP) systems, database tuning, and business intelligence solutions.',
      logoUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'OneClick eCommerce',
      industry: 'technology',
      address: 'phnom_penh',
      website: 'https://www.oneclick.com.kh',
      description: 'OneClick eCommerce empowers small businesses with digital storefront solutions, online payment gateways, and automated social commerce bots.',
      logoUrl: 'https://images.unsplash.com/photo-1522204523234-8729aa6e3d5f?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Pixel Perfect Design',
      industry: 'technology',
      address: 'battambang',
      website: 'https://www.pixelperfect.com.kh',
      description: 'Pixel Perfect is a creative design studio producing professional interfaces, vector assets, and visual communications for regional startups.',
      logoUrl: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Angkor Web Studio',
      industry: 'technology',
      address: 'siem_reap',
      website: 'https://www.angkorweb.com.kh',
      description: 'Angkor Web Studio builds custom WordPress sites, luxury hotel booking layouts, and responsive marketing landing pages for global travelers.',
      logoUrl: 'https://images.unsplash.com/photo-1508921912186-1d1a45ebb3c1?w=150&h=150&fit=crop&q=80',
    },

    // --- Finance / Banking (20 Companies) ---
    {
      name: 'ABA Bank',
      industry: 'finance',
      address: 'phnom_penh',
      website: 'https://www.ababank.com',
      description: 'ABA Bank is Cambodia\'s leading private financial institution, recognized globally for its digital banking platforms, mobile apps, and robust customer service.',
      logoUrl: 'https://images.unsplash.com/photo-1501167786227-4cba60f6d58f?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Wing Bank',
      industry: 'finance',
      address: 'phnom_penh',
      website: 'https://www.wingbank.com.kh',
      description: 'Wing Bank (Cambodia) Plc is a pioneer of mobile banking services in Cambodia, providing secure money transfers, digital payments, and retail banking.',
      logoUrl: 'https://images.unsplash.com/photo-1580519542036-c47de6196ba5?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'ACLEDA Bank',
      industry: 'finance',
      address: 'phnom_penh',
      website: 'https://www.acledabank.com.kh',
      description: 'ACLEDA Bank Plc. is a public commercial bank providing extensive microfinance, retail banking, digital payments, and international trade services.',
      logoUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Sathapana Bank',
      industry: 'finance',
      address: 'phnom_penh',
      website: 'https://www.sathapana.com.kh',
      description: 'Sathapana Bank is a leading commercial bank in Cambodia, offering comprehensive banking services, loans, and corporate accounts nationwide.',
      logoUrl: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Canadia Bank',
      industry: 'finance',
      address: 'phnom_penh',
      website: 'https://www.canadiabank.com.kh',
      description: 'Canadia Bank is one of the largest local commercial banks in Cambodia, serving corporate and retail customers since 1991.',
      logoUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Phillip Bank',
      industry: 'finance',
      address: 'phnom_penh',
      website: 'https://www.phillipbank.com.kh',
      description: 'Phillip Bank offers a wide range of retail, corporate, and digital financial products, backed by the Singaporean financial group PhillipCapital.',
      logoUrl: 'https://images.unsplash.com/photo-1534951009808-766178b47a4f?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'AMK Microfinance',
      industry: 'finance',
      address: 'phnom_penh',
      website: 'https://www.amkcambodia.com',
      description: 'AMK Microfinance Institution is a leading microfinance provider focusing on small-holder agricultural loans, rural savings, and insurance.',
      logoUrl: 'https://images.unsplash.com/photo-1462206092226-f7102b660719?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'BRED Bank Cambodia',
      industry: 'finance',
      address: 'phnom_penh',
      website: 'https://www.bredcambodia.com',
      description: 'BRED Bank Cambodia is the only European bank operating in Cambodia, offering high-standard private, commercial, and premier banking solutions.',
      logoUrl: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'J Trust Royal Bank',
      industry: 'finance',
      address: 'phnom_penh',
      website: 'https://www.jtrustroyal.com',
      description: 'J Trust Royal Bank is a commercial bank delivering high-level security, international corporate trade finance, and premier savings accounts.',
      logoUrl: 'https://images.unsplash.com/photo-1508169351866-74760bbbc915?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Prince Bank',
      industry: 'finance',
      address: 'phnom_penh',
      website: 'https://www.princebank.com.kh',
      description: 'Prince Bank Plc. is a commercial bank focusing on high-net-worth individuals, SME loans, corporate credit, and advanced mobile banking.',
      logoUrl: 'https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Vattanac Bank',
      industry: 'finance',
      address: 'phnom_penh',
      website: 'https://www.vattanacbank.com',
      description: 'Vattanac Bank offers boutique personal banking services, premier investment accounts, and digital gold trading products.',
      logoUrl: 'https://images.unsplash.com/photo-1538356111088-74a4891d28a3?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Hattha Bank',
      industry: 'finance',
      address: 'phnom_penh',
      website: 'https://www.hatthabank.com',
      description: 'Hattha Bank is a subsidiary of Krungsri Group, delivering retail deposits, micro-loans, commercial cash management, and insurance.',
      logoUrl: 'https://images.unsplash.com/photo-1541354329998-f437a24781ff?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'FTB Bank',
      industry: 'finance',
      address: 'phnom_penh',
      website: 'https://www.ftbbank.com',
      description: 'Foreign Trade Bank of Cambodia (FTB) is Cambodia\'s first domestic commercial bank, providing foreign exchange and trade clearing.',
      logoUrl: 'https://images.unsplash.com/photo-1544377193-33dcf4d68fb5?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'PPCBank',
      industry: 'finance',
      address: 'phnom_penh',
      website: 'https://www.ppcbank.com.kh',
      description: 'Phnom Penh Commercial Bank (PPCBank) is a joint venture bank offering commercial cash management and Japanese-standard service quality.',
      logoUrl: 'https://images.unsplash.com/photo-1563013544-824ae1d704d3?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Lola Microfinance',
      industry: 'finance',
      address: 'battambang',
      website: 'https://www.lolamfi.com',
      description: 'Lola MFI provides micro-leasing, community-based self-help savings plans, and agricultural cooperative capital in Northwest provinces.',
      logoUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Fortress Insurance',
      industry: 'finance',
      address: 'phnom_penh',
      website: 'https://www.fortressins.com',
      description: 'Fortress Insurance offers comprehensive commercial risk underwriting, cargo marine insurance, and custom employee healthcare packages.',
      logoUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'CamboPay Solutions',
      industry: 'finance',
      address: 'phnom_penh',
      website: 'https://www.cambopay.com',
      description: 'CamboPay offers custom digital payment terminals, POS merchant setups, and online invoice settlement engines for SMEs.',
      logoUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Goldstone Securities',
      industry: 'finance',
      address: 'phnom_penh',
      website: 'https://www.goldstone.com.kh',
      description: 'Goldstone Securities provides CSX securities brokerage, corporate IPO advisory, capital fundraising, and wealth portfolio management.',
      logoUrl: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Lotus Wealth Advisory',
      industry: 'finance',
      address: 'siem_reap',
      website: 'https://www.lotuswealth.com',
      description: 'Lotus Wealth provides boutique asset management, hotel real-estate investment advisory, and offshore asset structure setup services.',
      logoUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Sovan Real Estate Finance',
      industry: 'finance',
      address: 'phnom_penh',
      website: 'https://www.sovanfinance.com',
      description: 'Sovan Finance delivers property mortgages, construction bridge loans, and retail lease financing solutions for modern urban condominiums.',
      logoUrl: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=150&h=150&fit=crop&q=80',
    },

    // --- Education (20 Companies) ---
    {
      name: 'CamEd Business School',
      industry: 'education',
      address: 'phnom_penh',
      website: 'https://www.cam-ed.com',
      description: 'CamEd Business School is specialized in teaching accounting and finance. It is the premier institution producing certified ACCA graduates in Cambodia.',
      logoUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Paragon International University',
      industry: 'education',
      address: 'phnom_penh',
      website: 'https://www.paragon.edu.kh',
      description: 'Paragon International University (formerly Zaman University) offers high-quality bilingual programs in engineering, IT, and political sciences.',
      logoUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf36?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'American University of Phnom Penh',
      industry: 'education',
      address: 'phnom_penh',
      website: 'https://www.aupp.edu.kh',
      description: 'American University of Phnom Penh (AUPP) is a leading higher education institution offering dual-degree US accredited undergraduate programs.',
      logoUrl: 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Liger Leadership Academy',
      industry: 'education',
      address: 'phnom_penh',
      website: 'https://www.ligeracademy.org',
      description: 'Liger Leadership Academy offers a project-based entrepreneurship curriculum to build future change-makers and social pioneers.',
      logoUrl: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Norton University',
      industry: 'education',
      address: 'phnom_penh',
      website: 'https://www.norton.edu.kh',
      description: 'Norton University is the first private university in Cambodia, offering extensive programs in engineering, technology, and administration.',
      logoUrl: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5c?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Royal University of Phnom Penh',
      industry: 'education',
      address: 'phnom_penh',
      website: 'https://www.rupp.edu.kh',
      description: 'RUPP is the national university of Cambodia, offering extensive degrees in sciences, humanities, languages, and social engineering.',
      logoUrl: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Institute of Technology of Cambodia',
      industry: 'education',
      address: 'phnom_penh',
      website: 'https://www.itc.edu.kh',
      description: 'ITC, commonly known as "Techno", is the premier engineering and industrial research institution in the Kingdom of Cambodia.',
      logoUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Zaman International School',
      industry: 'education',
      address: 'phnom_penh',
      website: 'https://www.zaman.edu.kh',
      description: 'Zaman International School offers premium Cambridge-aligned kindergarten, primary, and secondary education.',
      logoUrl: 'https://images.unsplash.com/photo-1588072432836-e10032774350?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Western University',
      industry: 'education',
      address: 'battambang',
      website: 'https://www.western.edu.kh',
      description: 'Western University Battambang offers specialized programs in agricultural sciences, accounting, and English literature.',
      logoUrl: 'https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Angkor University',
      industry: 'education',
      address: 'siem_reap',
      website: 'https://www.angkor.edu.kh',
      description: 'Angkor University provides high-quality vocational training, nursing degrees, and tourism management credentials in Siem Reap.',
      logoUrl: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Dewey International University',
      industry: 'education',
      address: 'battambang',
      website: 'https://www.diu.edu.kh',
      description: 'Dewey University is a leading academic institution in Northwestern Cambodia, promoting creative research and critical thinking.',
      logoUrl: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Harpswell Foundation Center',
      industry: 'education',
      address: 'phnom_penh',
      website: 'https://www.harpswellfoundation.org',
      description: 'Harpswell provides leadership training, critical thinking instruction, and dormitory spaces for outstanding female university students.',
      logoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Beltei International Academy',
      industry: 'education',
      address: 'phnom_penh',
      website: 'https://www.beltei.edu.kh',
      description: 'Beltei International School is famous for its intensive English training, national curriculum preparation, and corporate discipline.',
      logoUrl: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Paul Dubrule Academy',
      industry: 'education',
      address: 'siem_reap',
      website: 'https://www.ecolepauldubrule.org',
      description: 'Paul Dubrule is a premier vocational hospitality school preparing local students for luxury hotel and restaurant careers.',
      logoUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Salamat Language Center',
      industry: 'education',
      address: 'phnom_penh',
      website: 'https://www.salamatlc.com',
      description: 'Salamat Language Center is a boutique academy offering business English, Chinese, and advanced Khmer for foreign executives.',
      logoUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Sovan Educational Group',
      industry: 'education',
      address: 'phnom_penh',
      website: 'https://www.sovanschool.edu.kh',
      description: 'Sovan Group operates premium kindergartens and primary schools specializing in early child development and creative play.',
      logoUrl: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Creative Kids Cambodia',
      industry: 'education',
      address: 'phnom_penh',
      website: 'https://www.creativekids.com.kh',
      description: 'Creative Kids provides STEAM education, robotic coding tutorials, and logic workshops for young tech pioneers.',
      logoUrl: 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Siem Reap Culinary Institute',
      industry: 'education',
      address: 'siem_reap',
      website: 'https://www.srculinary.edu.kh',
      description: 'Siem Reap Culinary School teaches fine pastry art, traditional Khmer recipes, and advanced kitchen sanitization standards.',
      logoUrl: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Apex Academy',
      industry: 'education',
      address: 'phnom_penh',
      website: 'https://www.apexacademy.com.kh',
      description: 'Apex offers professional training in digital marketing, corporate management, and HR development.',
      logoUrl: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Bloom Education Center',
      industry: 'education',
      address: 'sihanoukville',
      website: 'https://www.bloomeducation.org',
      description: 'Bloom provides community scholarships, vocational sewing apprenticeships, and computer literacy classes for local coastal families.',
      logoUrl: 'https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?w=150&h=150&fit=crop&q=80',
    },

    // --- Food & Beverage (15 Companies) ---
    {
      name: 'Brown Coffee',
      industry: 'fnb',
      address: 'phnom_penh',
      website: 'https://www.browncoffee.com.kh',
      description: 'Brown Coffee & Bakery is a homegrown Cambodian cafe brand, celebrated for roasting premium beans and designing creative spaces.',
      logoUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'KOI Thé Cambodia',
      industry: 'fnb',
      address: 'phnom_penh',
      website: 'https://www.koithe.com',
      description: 'KOI Thé is Cambodia\'s favorite bubble milk tea brand, famous for its freshly-made golden bubbles and signature macchiato series.',
      logoUrl: 'https://images.unsplash.com/photo-1541658016709-82535e94bc69?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Starbucks Cambodia',
      industry: 'fnb',
      address: 'phnom_penh',
      website: 'https://www.starbucks.com.kh',
      description: 'Starbucks coffee houses provide premium arabica coffee, seasonal cold brews, and elegant workspace lounge tables.',
      logoUrl: 'https://images.unsplash.com/photo-1507133750040-4a8f57021571?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Park Cafe',
      industry: 'fnb',
      address: 'phnom_penh',
      website: 'https://www.parkcafe.com.kh',
      description: 'Park Cafe serves MSG-free healthy Kuy Teav and organic Cambodian coffee for business people and families.',
      logoUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'The Pizza Company',
      industry: 'fnb',
      address: 'phnom_penh',
      website: 'https://www.thepizzacompany.com.kh',
      description: 'The Pizza Company is Cambodia\'s leading pizza and pasta franchise restaurant, owned and operated locally by Express Food Group.',
      logoUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Java Creative Cafe',
      industry: 'fnb',
      address: 'phnom_penh',
      website: 'https://www.javacafe.com',
      description: 'Java Creative Cafe hosts local visual art exhibits, performing theater programs, and artisan organic food options.',
      logoUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Khema Restaurant',
      industry: 'fnb',
      address: 'phnom_penh',
      website: 'https://www.khema-restaurant.com',
      description: 'Khema offers high-class French fine dining, international cheeses, premium charcuterie, and gourmet bakery buffets.',
      logoUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'KFC Cambodia',
      industry: 'fnb',
      address: 'phnom_penh',
      website: 'https://www.kfc.com.kh',
      description: 'KFC Cambodia is a highly popular quick-service chicken brand offering fried chicken, burgers, and family meals.',
      logoUrl: 'https://images.unsplash.com/photo-1513639778249-caee7297b61f?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Lotteria Cambodia',
      industry: 'fnb',
      address: 'phnom_penh',
      website: 'https://www.lotteria.com.kh',
      description: 'Lotteria serves premium Korean-style burgers, cheese sticks, and crispy seasoned chicken snacks.',
      logoUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Gloria Jean\'s Coffees',
      industry: 'fnb',
      address: 'phnom_penh',
      website: 'https://www.gloriajeanscoffees.com.kh',
      description: 'Gloria Jean\'s is a global Australian coffee franchise serving high-quality specialty coffee and pastries.',
      logoUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Bakehouse Cambodia',
      industry: 'fnb',
      address: 'siem_reap',
      website: 'https://www.bakehouse.com.kh',
      description: 'Bakehouse serves authentic sourdough loaves, croissants, and gourmet pastries to travelers in Siem Reap.',
      logoUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Malis Restaurant',
      industry: 'fnb',
      address: 'phnom_penh',
      website: 'https://www.malis-restaurant.com',
      description: 'Malis is a famous fine-dining venue celebrating Living Cambodian Cuisine, crafted by Master Chef Luu Meng.',
      logoUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Anise Khmer Eatery',
      industry: 'fnb',
      address: 'siem_reap',
      website: 'https://www.anisekhmer.com',
      description: 'Anise serves authentic home-style Khmer fish amok, lemongrass chicken, and organic local fruit shakes.',
      logoUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Battambang Craft Brews',
      industry: 'fnb',
      address: 'battambang',
      website: 'https://www.bbcrafts.com',
      description: 'Battambang Craft Brews produces artisanal local craft soda, organic ginger beer, and zero-sugar tonics.',
      logoUrl: 'https://images.unsplash.com/photo-1600788886242-5c96aabe3757?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Green Coast Salad Bar',
      industry: 'fnb',
      address: 'sihanoukville',
      website: 'https://www.greencoast.com',
      description: 'Green Coast is a coastal healthy salad parlor offering raw cold-pressed juices, organic wraps, and vegan bowls.',
      logoUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=150&h=150&fit=crop&q=80',
    },

    // --- Retail / E-Commerce (20 Companies) ---
    {
      name: 'Aeon Mall Cambodia',
      industry: 'retail',
      address: 'phnom_penh',
      website: 'https://www.aeonmallcambodia.com',
      description: 'Aeon Mall is Cambodia\'s largest international shopping mall operator, managing multiple mega-complexes.',
      logoUrl: 'https://images.unsplash.com/photo-1519208495603-45a1683b9e43?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Makro Cambodia',
      industry: 'retail',
      address: 'phnom_penh',
      website: 'https://www.makrocambodia.com',
      description: 'Siam Makro provides large-scale wholesale food and non-food product distribution to catering businesses.',
      logoUrl: 'https://images.unsplash.com/photo-1534723328310-e82dad3ee43f?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Lucky Supermarket',
      industry: 'retail',
      address: 'phnom_penh',
      website: 'https://www.luckysupermarket.com.kh',
      description: 'Lucky is the biggest grocery retailer in Cambodia, delivering fresh imported produce, meat, and dry goods.',
      logoUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Zando Cambodia',
      industry: 'retail',
      address: 'phnom_penh',
      website: 'https://www.zando.com.kh',
      description: 'Zando is a top fashion retailer in Cambodia, offering global casual clothing, accessories, and shoes.',
      logoUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Ten11 Casualwear',
      industry: 'retail',
      address: 'phnom_penh',
      website: 'https://www.ten11.com.kh',
      description: 'Ten11 is a popular local fashion label known for relaxed streetwear, quality denims, and graphic tees.',
      logoUrl: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Pedro Shoes Cambodia',
      industry: 'retail',
      address: 'phnom_penh',
      website: 'https://www.pedroshoes.com',
      description: 'Pedro provides refined contemporary footwear, bags, and luxury accessories for business professionals.',
      logoUrl: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Charles & Keith Cambodia',
      industry: 'retail',
      address: 'phnom_penh',
      website: 'https://www.charleskeith.com',
      description: 'Charles & Keith is a major international fashion house providing shoes, handbags, and accessories.',
      logoUrl: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Adidas Cambodia',
      industry: 'retail',
      address: 'phnom_penh',
      website: 'https://www.adidas.com',
      description: 'Adidas flagship store in Cambodia provides premium running shoes, training gear, and sport activewear.',
      logoUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Puma Cambodia',
      industry: 'retail',
      address: 'phnom_penh',
      website: 'https://www.puma.com',
      description: 'Puma offers premium athletic footwear, soccer boots, hoodies, and fitness bags to local athletes.',
      logoUrl: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Nata Genuine Leather',
      industry: 'retail',
      address: 'phnom_penh',
      website: 'https://www.natafootwear.com',
      description: 'Nata specializes in bespoke hand-sewn leather shoes, belts, and luxury wallets for men.',
      logoUrl: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Little Fashion',
      industry: 'retail',
      address: 'phnom_penh',
      website: 'https://www.littlefashion.com.kh',
      description: 'Little Fashion (L1F) is one of Cambodia\'s first online-to-offline e-commerce sites selling dresses.',
      logoUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Sovanna Shopping Center',
      industry: 'retail',
      address: 'phnom_penh',
      website: 'https://www.sovannashopping.com',
      description: 'Sovanna Mall offers domestic retail storefronts, family gaming arcades, and a diverse local food court.',
      logoUrl: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Angkor Organic Mart',
      industry: 'retail',
      address: 'siem_reap',
      website: 'https://www.angkororganic.com',
      description: 'Angkor Organic sells eco-friendly local honey, Kampot pepper, brown rice, and handmade soaps.',
      logoUrl: 'https://images.unsplash.com/photo-1471193945509-9ad0617afabf?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Battambang Silk Weavers',
      industry: 'retail',
      address: 'battambang',
      website: 'https://www.bbsilk.com',
      description: 'Silk Weavers sells premium hand-woven golden silk scarves, traditional sarongs, and table runners.',
      logoUrl: 'https://images.unsplash.com/photo-1528701802914-4e247c60209c?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Coastal Souvenir Shop',
      industry: 'retail',
      address: 'sihanoukville',
      website: 'https://www.coastalsouvenirs.com',
      description: 'Coastal Souvenirs sells seashell crafts, beach towels, sun hats, and local coconut massage oils.',
      logoUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'SmartLife Appliances',
      industry: 'retail',
      address: 'phnom_penh',
      website: 'https://www.smartlife.com.kh',
      description: 'SmartLife distributes smart home vacuum bots, automated air purifiers, and security cameras.',
      logoUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Heritage Book Store',
      industry: 'retail',
      address: 'phnom_penh',
      website: 'https://www.heritagebooks.com.kh',
      description: 'Heritage Books sells English and Khmer textbooks, educational journals, and stationery.',
      logoUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'Active Sports Cambodia',
      industry: 'retail',
      address: 'phnom_penh',
      website: 'https://www.activesports.com.kh',
      description: 'Active Sports sells exercise treadmills, dumbbell sets, swimming gear, and yoga mats.',
      logoUrl: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'EcoGreen Home',
      industry: 'retail',
      address: 'siem_reap',
      website: 'https://www.ecogreen.com.kh',
      description: 'EcoGreen sells bamboo kitchenware, biodegradable trash bags, and organic garden seeds.',
      logoUrl: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=150&h=150&fit=crop&q=80',
    },
    {
      name: 'BabyBloom Boutique',
      industry: 'retail',
      address: 'phnom_penh',
      website: 'https://www.babybloom.com.kh',
      description: 'BabyBloom sells premium organic baby clothing, imported strollers, and safe wooden toys.',
      logoUrl: 'https://images.unsplash.com/photo-1515488042361-404e9250afef?w=150&h=150&fit=crop&q=80',
    },

    // --- Programmatic / Additional Companies to reach 100 ---
    ...Array.from({ length: 20 }).map((_, i) => ({
      name: `Innovate Tech ${i + 1}`,
      industry: 'technology',
      address: i % 2 === 0 ? 'phnom_penh' : 'siem_reap',
      website: `https://www.innovatetech${i + 1}.com`,
      description: `Innovate Tech ${i + 1} is a pioneer in digital cloud strategy, custom enterprise resource systems, and agile consulting.`,
      logoUrl: `https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=150&h=150&fit=crop&q=80`,
    })),
  ];

  for (const data of companiesData) {
    try {
      await companyRepo.save(companyRepo.create(data));
    } catch (err) {
      console.error(`Failed to seed company: ${data.name}`, err);
    }
  }

  console.log('100 Companies seeded successfully!');
}
